### ISSUE TITLE
这个phalcon-middleware可用么？

### ISSUE THREAD

**Issue by domyhero** [limingxinleo/x-phalcon-middleware#1]
你好，我运行了simple-subcontrollers.phalcon这个项目。
结果报错：[Fri, 03 Nov 17 16:11:18 +0800][ERROR] Declaration of Xin\Phalcon\Middleware\Mvc\Dispatcher::callActionMethod($handler, $actionMethod, $params = Array) should be compatible with Phalcon\Dispatcher::callActionMethod($handler, $actionMethod, ?array $params = NULL) in /data/wwwroot/phalcon-mvc/vendor/limingxinleo/x-phalcon-middleware/src/Middleware/Mvc/Dispatcher.php line 0

**Comment by limingxinleo** [comment]
请问你phalcon 版本是什么

**Comment by domyhero** [comment]
phalcon7

**Comment by domyhero** [comment]
最新的3.2

**Comment by domyhero** [comment]
重写的这个方法 Xin\Phalcon\Middleware\Mvc\Dispatcher::callActionMethod  注释掉就OK

**Comment by limingxinleo** [comment]
奇怪，我这里可以的。。
如果你注释了这个方法，那middleware功能就没办法使用了。。
能把你php版本和phalcon具体版本发给我吧
~~~
php -v
php --ri phalcon
~~~

**Comment by domyhero** [comment]
![image](https://user-images.githubusercontent.com/7158563/32365716-ec9d52d2-c0b5-11e7-9809-fcdb534004c8.png)
php 7.1.8   phalcon 3.2.2

**Comment by limingxinleo** [comment]
我找到问题了。。我刚刚写的middleware 在php 7.1里有个BUG，请稍等，我改一下
如果你不需要middleware功能
你可以主动改
app/core/Services/Mvc/Dispatcher.php
使用phalcon默认的dispatcher
~~~
$dispatcher = new \Phalcon\Mvc\Dispatcher();
// 使用x-phalcon-middleware重写的Dispatcher
// $dispatcher = new MvcDispatcher();
$dispatcher->setDefaultNamespace('App\Controllers');
~~~

**Comment by limingxinleo** [comment]
BUG已经修复了，你可以拉simple-subcontrollers.phalcon最新tag的代码进行测试了。
谢谢你的issue

**Comment by limingxinleo** [comment]
如果还有BUG，麻烦再通知我，谢谢！

**Comment by domyhero** [comment]
多谢作者的修复。后面有问题，我会详细整理到issue

**Comment by domyhero** [comment]
建议能够兼容一下 php7.0 php7.1, 不要一个PHP版本都要重命名一个类来继承\Phalcon\Mvc\Dispatcher

**Comment by domyhero** [comment]
middleware php 7.1使用，运行发现模板报错了。
![image](https://user-images.githubusercontent.com/7158563/32422857-ccb577e0-c2dd-11e7-849d-14b94bdecc47.png)

我使用时改了 app/core/Services/Mvc/Dispatcher.php 使用PHP7.1
`
use Xin\Phalcon\Middleware\Mvc\Dispatcher71 as MvcDispatcher;
//             $dispatcher = new \Phalcon\Mvc\Dispatcher();
            // 使用x-phalcon-middleware重写的Dispatcher
            $dispatcher = new MvcDispatcher();
            $dispatcher->setDefaultNamespace('App\Controllers');
            // 分配事件管理器到分发器
            $dispatcher->setEventsManager($eventsManager);
`

**Comment by domyhero** [comment]
使用phalcon默认的dispatcher，不使用middleware  同样也会出现模板编译报错

**Comment by limingxinleo** [comment]
cphalcon打包的php7.1和php7，对于这个函数的入参不一样。。。如果不修改cphalcon源码，只能这样了。。。
